# Sample .travis.yml for R projects.
#
# See the r-travis repo and its wiki 
#   https://github.com/craigcitro/r-travis/wiki
#   https://github.com/eddelbuettel/r-travis/

language: c

env:
  global:
    - PKG_CFLAGS="-g -O3 -Wall -pedantic -I../inst/include -DLOGGER_LEVEL=LL_WARN"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-vignettes --no-manual"
  matrix:
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - R_CHECK_ARGS="--as-cran" _R_CHECK_CRAN_INCOMING_=TRUE


before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget r-cran-runit
  - ./travis-tool.sh install_r Rcpp
  - ./travis-tool.sh install_deps
#  - ./travis-tool.sh install_r RcppArmadillo 
#  - ./travis-tool.sh install_github eddelbuettel/bh

script: 
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change